---
dependency:
  name: galaxy
  options:
    requirements-file: ../shared/requirements.yml

driver:
  name: docker

platforms:
  # --- UBUNTU 24.04 (Noble) ---
  - name: hardening-ubuntu2404
    image: ubuntu:24.04
    dockerfile: ../shared/Dockerfile.j2
    privileged: true
    tmpfs:
      - /run
      - /run/lock
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    shm_size: '512m'
    cgroupns_mode: host
    command: "/lib/systemd/systemd"

provisioner:
  name: ansible
  playbooks:
    prepare: ../default/prepare.yml
    converge: ../default/converge.yml
    verify: ../default/verify.yml
  config_options:
    defaults:
      interpreter_python: auto_silent
      inject_facts_as_vars: false
      host_key_checking: False
  inventory:
    host_vars:
      hardening-ubuntu2404:
        ansible_user: root

verifier:
  name: ansible
