---
dependency:
  name: galaxy
  options:
    requirements-file: ../shared/requirements.yml

driver:
  name: docker

platforms:
  # --- DEBIAN 12 (Bookworm) ---
  - name: hardening-debian12
    image: debian:12
    dockerfile: ../shared/Dockerfile.j2
    privileged: true
    tmpfs:
      - /run
      - /run/lock
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    shm_size: '512m'
    cgroupns_mode: host
    command: "/lib/systemd/systemd"

  # --- DEBIAN 13 (Trixie) ---
  - name: hardening-debian13
    image: debian:13
    dockerfile: ../shared/Dockerfile.j2
    privileged: true
    tmpfs:
      - /run
      - /run/lock
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    shm_size: '512m'
    cgroupns_mode: host
    command: "/lib/systemd/systemd"

  # --- UBUNTU 22.04 (Jammy) ---
  - name: hardening-ubuntu2204
    image: ubuntu:22.04
    dockerfile: ../shared/Dockerfile.j2
    privileged: true
    tmpfs:
      - /run
      - /run/lock
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    shm_size: '512m'
    cgroupns_mode: host
    command: "/lib/systemd/systemd"

  # --- UBUNTU 24.04 (Noble) ---
  - name: hardening-ubuntu2404
    image: ubuntu:24.04
    dockerfile: ../shared/Dockerfile.j2
    privileged: true
    tmpfs:
      - /run
      - /run/lock
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    shm_size: '512m'
    cgroupns_mode: host
    command: "/lib/systemd/systemd"

provisioner:
  name: ansible
  playbooks:
    prepare: prepare.yml
    converge: converge.yml
    verify: verify.yml
  config_options:
    defaults:
      interpreter_python: auto_silent
      inject_facts_as_vars: false
      host_key_checking: False
  inventory:
    host_vars:
      hardening-debian12:
        ansible_user: root
      hardening-debian13:
        ansible_user: root
      hardening-ubuntu2204:
        ansible_user: root
      hardening-ubuntu2404:
        ansible_user: root

verifier:
  name: ansible
